
[functions.ensure-profile-schema]
enabled = true
verify_jwt = true
import_map = "./functions/ensure-profile-schema/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ensure-profile-schema/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ensure-profile-schema/*.html" ]
